name: CMake CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build: 
    name: build project
    runs-on: macos-latest
    strategy:
      matrix:
        cmake_version: [3.10]
    steps: 
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          brew update
          brew install opencv

      - name: Configure CMake
        run: cmake -Bbuild -S. -DOpenCV_DIR=/opt/homebrew/Cellar/opencv/4.9.0_10/lib/cmake/opencv4

      - name: Generate build files in build dir
        run: cmake -B build

      - name: Build project
        run: cmake --build build

  # test: 
  #   name: run tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: run all unit tests
  #       run: ctest




    
      