name: CMake CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build: 
    name: build project
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cmake_version: [3.10, 3.15, 3.20]
    steps: 
      - uses: actions/checkout@v4

      - name: create and enter build dir
        run: |
          mkdir build
          cd build

      - name: run cmake
        run: cmake ..

      - name: run make
        run: make

  # test: 
  #   name: run tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: run all unit tests
  #       run: ctest




    
      